package com.company.View;

import com.company.Controller.Gauss;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;

public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        eqtText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eqtTable = new javax.swing.JTable();
        jCalcButton = new javax.swing.JButton();
        jTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eqtText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eqtText.setText("Insira os valores da equação (campos vazios equivalem a 0):");

        eqtTable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        eqtTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "b"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        eqtTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(eqtTable);
        eqtTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jCalcButton.setText("Calcular");
        jCalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalcButtonActionPerformed(evt);
            }
        });

        jTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTitle.setText("Eliminação de Gauss");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jCalcButton))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(eqtText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 134, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addComponent(jTitle)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jTitle)
                                .addGap(156, 156, 156)
                                .addComponent(eqtText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(jCalcButton)
                                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>

    private void jCalcButtonActionPerformed(java.awt.event.ActionEvent evt) {
        double[][] data = new double[10][11];

        for(int i = 0; i < 10; i++) {
            for(int j = 0; j < 11; j++) {
                if(eqtTable.getValueAt(i,j) == null) {
                    data[i][j] = 0;
                } else {
                    data[i][j] = (Double) eqtTable.getValueAt(i, j);
                }
            }
        }

        Gauss g = new Gauss(data);
        resultFrame(g);
    }

    public void resultFrame(Gauss g) {
        JTextArea t1 = new JTextArea();
        JTextArea t2 = new JTextArea();
        JFrame jr = new JFrame();

        jr.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        jr.setLayout(null);
        jr.setSize(1200,800);
        jr.setVisible(true);


        t1.setColumns(20);
        t1.setRows(5);
        t1.setFont(new Font("Segoe UI", Font.PLAIN,12));
        t1.setBounds(40,25,550,700);

        t2.setColumns(20);
        t2.setRows(5);
        t2.setFont(new Font("Segoe UI", Font.PLAIN,12));
        t2.setBounds(600,25,550,700);

        jr.add(t1);
        jr.add(t2);
        t1.setVisible(false);
        t1.setVisible(true);
        t2.setVisible(false);
        t2.setVisible(true);

        t1.setText("Gauss:" + '\n' + g.retorno());
        t2.setText("LU:" + '\n' + '\n' + g.retorno_L() + '\n' + '\n' + g.retorno_U() + '\n' + '\n' + g.retorno_LU());

    }

  /**  public void resultLU(Gauss g) {
        JTextArea t1LU = new JTextArea();
        JFrame jrLU = new JFrame();

        jrLU.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        jrLU.setLayout(null);
        jrLU.setSize(1200,800);
        jrLU.setVisible(true);


        t1LU.setColumns(20);
        t1LU.setRows(5);
        t1LU.setFont(new Font("Segoe UI", Font.PLAIN,12));
        t1LU.setBounds(40,25,1100,700);

        jrLU.add(t1LU);
        t1LU.setVisible(false);
        t1LU.setVisible(true);

        t1LU.setText(g.retorno());

    } */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    public javax.swing.JTable eqtTable;
    private javax.swing.JLabel eqtText;
    private javax.swing.JButton jCalcButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTitle;
    // End of variables declaration
}
